# Generated by Django 3.0 on 2020-07-16 20:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import main.utils
import students.mixins.common_functions_mixin
import students.mixins.compensatory_exams_functions_mixin
import students.mixins.result_paper_functions_mixin
import students.mixins.semester_fucntions_mixin
import students.mixins.subject_result_function_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_leader_name', models.CharField(max_length=255)),
                ('entry', models.CharField(choices=[('regular', 'Regular'), ('associate', 'Associate')], default='نظامي', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('repeater', 'Repeater')], default='مستجد', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('part2', models.BooleanField(default=False)),
                ('part3', models.BooleanField(default=False)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('estimate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['the_class'],
            },
            bases=(models.Model, students.mixins.result_paper_functions_mixin.ResultPaperFunctionMixin, students.mixins.common_functions_mixin.FinalResultsMixin),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], default='1', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('estimate', models.CharField(blank=True, max_length=255, null=True)),
                ('results_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.ResultsPaper')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, students.mixins.semester_fucntions_mixin.SemesterFunctionMixin, students.mixins.common_functions_mixin.FinalResultsMixin),
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('std_exam_grade', models.PositiveIntegerField(default=0)),
                ('std_year_works_grade', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_results', to='students.Semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_tables.Article')),
            ],
            options={
                'ordering': ['subject'],
            },
            bases=(models.Model, students.mixins.subject_result_function_mixin.SubjectResultFunctionMixin, students.mixins.common_functions_mixin.SubjectsResultsMixin),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('grand_father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('cell_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(choices=[('Libyan', 'Libyan'), ('Egyptian', 'Egyptian'), ('Tunisian', 'Tunisian'), ('Algerian', 'Algerian'), ('Moroccan', 'Moroccan'), ('Somali', 'Somali'), ('Sudanese', 'Sudanese'), ('Syrian', 'Syrian'), ('Qatari', 'Qatari'), ('Iraqi', 'Iraqi'), ('Palestinian', 'Palestinian'), ('Jordanian', 'Jordanian'), ('Saudi', 'Saudi'), ('Nigerian', 'Nigerian'), ('Turkish', 'Turkish'), ('Lebanese', 'Lebanese'), ('Mauritanian', 'Mauritanian'), ('Emirati', 'Emirati')], default='ليبي', max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to=main.utils.students_image_random_name)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_tables.ClassRoom')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_tables.TheClass')),
            ],
        ),
        migrations.AddField(
            model_name='resultspaper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='students.Student'),
        ),
        migrations.AddField(
            model_name='resultspaper',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_tables.TheClass'),
        ),
        migrations.CreateModel(
            name='CompensatoryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('std_year_works_grade', models.PositiveIntegerField(default=0)),
                ('std_exam_grade', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('semester', models.CharField(choices=[('2', 'Second'), ('3', 'Third')], default='2', max_length=120)),
                ('part', models.CharField(choices=[('2', 'Second'), ('3', 'Third')], max_length=120)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('results_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_com_grades', to='students.ResultsPaper')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_grades', to='school_tables.Article')),
            ],
            options={
                'ordering': ['subject'],
            },
            bases=(models.Model, students.mixins.compensatory_exams_functions_mixin.CompensatoryExamsFunctionsMixin, students.mixins.common_functions_mixin.SubjectsResultsMixin),
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('order', models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], default='1', max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_grades', to='school_tables.Article')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school_tables.TheClass')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
