# Generated by Django 3.0.3 on 2020-04-26 16:54

from django.db import migrations, models
import django.db.models.deletion
import students.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_tabels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_leader_name', models.CharField(max_length=255)),
                ('entry', models.CharField(choices=[('نظامي', 'نظامي'), ('منتسب', 'منتسب')], default='نظامي', max_length=255)),
                ('status', models.CharField(choices=[('مستجد', 'مستجد'), ('معيد', 'معيد')], default='مستجد', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('part2', models.BooleanField(default=False)),
                ('part3', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['the_class'],
            },
            bases=(models.Model, students.mixins.FinalResultsMixin),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], default='1', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('results_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.ResultsPaper')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, students.mixins.FinalResultsMixin),
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('std_exam_grade', models.PositiveIntegerField(default=0)),
                ('std_year_works_grade', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_results', to='students.Semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_tabels.Article')),
            ],
            options={
                'ordering': ['subject'],
            },
            bases=(models.Model, students.mixins.SubjectsResultsMixin),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('grand_father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('ml', 'ذكر'), ('fl', 'أنثى')], max_length=255)),
                ('cell_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(choices=[('ليبي', 'ليبي'), ('مصري', 'مصري'), ('مغربي', 'مغربي'), ('جزائري', 'جزائري'), ('صومالي', 'صومالي'), ('تونسي', 'تونسي'), ('سوري', 'سوري'), ('سوداني', 'سوداني'), ('عراقي', 'عراقي'), ('قطري', 'قطري'), ('أردني', 'أردني'), ('فلسطيني', 'فلسطيني'), ('إماراتي', 'إماراتي'), ('سعودي', 'سعودي'), ('تركي', 'تركي'), ('نيجيري', 'نيجيري'), ('لبناني', 'لبناني')], default='ليبي', max_length=255)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_tabels.ClassRoom')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_tabels.TheClass')),
            ],
        ),
        migrations.AddField(
            model_name='resultspaper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='students.Student'),
        ),
        migrations.AddField(
            model_name='resultspaper',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_tabels.TheClass'),
        ),
        migrations.CreateModel(
            name='CompensatoryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('std_year_works_grade', models.PositiveIntegerField(default=0)),
                ('std_exam_grade', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('semester', models.CharField(choices=[('2', 'الثانية'), ('3', 'الثالثة')], default='2', max_length=120)),
                ('part', models.CharField(choices=[('2', 'الثاني'), ('3', 'الثالث')], max_length=120)),
                ('results_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_com_grades', to='students.ResultsPaper')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_grades', to='school_tabels.Article')),
            ],
            options={
                'ordering': ['subject'],
            },
            bases=(models.Model, students.mixins.SubjectsResultsMixin),
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveIntegerField(default=0)),
                ('exam_pass_grade', models.PositiveIntegerField(default=0)),
                ('grade_pass_subject', models.PositiveIntegerField(default=0)),
                ('year_works_grade', models.PositiveIntegerField(default=0)),
                ('order', models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], default='1', max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_grades', to='school_tabels.Article')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school_tabels.TheClass')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
