# Generated by Django 3.0.3 on 2020-05-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0001_initial'),
        ('students', '0002_auto_20200502_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultspaper',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_tabels.TheClass'),
        ),
    ]
