# Generated by Django 3.0.3 on 2020-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200502_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('ليبي', 'ليبي'), ('مصري', 'مصري'), ('مغربي', 'مغربي'), ('جزائري', 'جزائري'), ('صومالي', 'صومالي'), ('تونسي', 'تونسي'), ('سوري', 'سوري'), ('سوداني', 'سوداني'), ('عراقي', 'عراقي'), ('قطري', 'قطري'), ('أردني', 'أردني'), ('فلسطيني', 'فلسطيني'), ('إماراتي', 'إماراتي'), ('سعودي', 'سعودي'), ('تركي', 'تركي'), ('نيجيري', 'نيجيري'), ('لبناني', 'لبناني'), ('موريتاني', 'موريتاني')], default='ليبي', max_length=255),
        ),
    ]
