# Generated by Django 3.0.3 on 2020-05-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200514_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id_number',
            new_name='nid_number',
        ),
        migrations.AlterField(
            model_name='resultspaper',
            name='entry',
            field=models.CharField(choices=[('regular', 'Regular'), ('associate', 'Associate')], default='نظامي', max_length=255),
        ),
        migrations.AlterField(
            model_name='resultspaper',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('repeater', 'Repeater')], default='مستجد', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('ml', 'Male'), ('fl', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Libyan', 'Libyan'), ('Egyptian', 'Egyptian'), ('Tunisian', 'Tunisian'), ('Algerian', 'Algerian'), ('Moroccan', 'Moroccan'), ('Somali', 'Somali'), ('Sudanese', 'Sudanese'), ('Syrian', 'Syrian'), ('Qatari', 'Qatari'), ('Iraqi', 'Iraqi'), ('Palestinian', 'Palestinian'), ('Jordanian', 'Jordanian'), ('Saudi', 'Saudi'), ('Nigerian', 'Nigerian'), ('Turkish', 'Turkish'), ('Lebanese', 'Lebanese'), ('Mauritanian', 'Mauritanian'), ('Emirati', 'Emirati')], default='ليبي', max_length=255),
        ),
    ]
