# Generated by Django 3.0.3 on 2020-05-28 22:28

from django.db import migrations, models
import django_resized.forms
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200528_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to=main.utils.students_image_random_name),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255),
        ),
    ]
