# Generated by Django 3.0.3 on 2020-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200528_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspaper',
            name='total_summation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compensatoryexam',
            name='part',
            field=models.CharField(choices=[('2', 'Second'), ('3', 'Third')], max_length=120),
        ),
        migrations.AlterField(
            model_name='compensatoryexam',
            name='semester',
            field=models.CharField(choices=[('2', 'Second'), ('3', 'Third')], default='2', max_length=120),
        ),
    ]
