# Generated by Django 3.0.3 on 2020-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200610_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultspaper',
            name='total_summation',
        ),
        migrations.AddField(
            model_name='resultspaper',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
