# Generated by Django 3.0.3 on 2020-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theclass',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
