# Generated by Django 3.0.3 on 2020-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0002_theclass_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
