# Generated by Django 3.0.3 on 2020-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0003_classroom_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtabel',
            name='en_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
