# Generated by Django 3.0.3 on 2020-05-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0004_examtabel_en_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='article',
            new_name='en_subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='تاريخ', max_length=255),
            preserve_default=False,
        ),
    ]
