# Generated by Django 3.0.3 on 2020-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0006_remove_exam_en_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='theclass',
            name='en_name',
        ),
        migrations.AddField(
            model_name='article',
            name='en_name',
            field=models.CharField(default='Subject', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examtabel',
            name='exam_type',
            field=models.CharField(choices=[('1', 'Midterm'), ('2', 'Final'), ('3', 'Second Round'), ('4', 'Third Round')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='examtabel',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], default=1, max_length=255),
        ),
    ]
