# Generated by Django 3.0.3 on 2020-05-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0008_theclass_en_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theclass',
            name='en_name',
        ),
    ]
