# Generated by Django 3.0.3 on 2020-05-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0009_remove_theclass_en_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtabel',
            old_name='last_update_by',
            new_name='last_editor',
        ),
    ]
