# Generated by Django 3.0.3 on 2020-05-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0011_auto_20200523_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['the_date', 'start_time']},
        ),
    ]
