# Generated by Django 3.0.3 on 2020-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_tabels', '0012_auto_20200528_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtabel',
            name='exam_type',
            field=models.CharField(choices=[('1', 'Midterm'), ('2', 'Final'), ('3', 'Second Attempt'), ('4', 'Third Attempt')], default=1, max_length=255),
        ),
    ]
