# Generated by Django 3.0.3 on 2020-05-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolinfo',
            old_name='descritption',
            new_name='content',
        ),
    ]
