# Generated by Django 3.0.3 on 2020-05-06 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200506_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
