# Generated by Django 3.0.3 on 2020-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200506_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='english_name',
            field=models.CharField(default='the flag', max_length=255),
            preserve_default=False,
        ),
    ]
