# Generated by Django 3.0.3 on 2020-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schoolinfo_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
