# Generated by Django 3.0.3 on 2020-05-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='english_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainarticle',
            name='english_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
