# Generated by Django 3.0.3 on 2020-05-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200506_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='school_phone',
            field=models.CharField(default='092734324', max_length=255),
            preserve_default=False,
        ),
    ]
