# Generated by Django 3.0.3 on 2020-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_schoolinfo_school_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
