# Generated by Django 3.0.3 on 2020-06-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TheClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subjects_num', models.PositiveSmallIntegerField(default=7)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subjects', models.ManyToManyField(blank=True, to='school_tables.Article')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_1', to='school_tables.Article')),
                ('class_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_2', to='school_tables.Article')),
                ('class_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_3', to='school_tables.Article')),
                ('class_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_4', to='school_tables.Article')),
                ('class_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_5', to='school_tables.Article')),
                ('class_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_6', to='school_tables.Article')),
                ('class_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_7', to='school_tables.Article')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='school_tables.ClassRoom')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_tables.Day')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=50)),
                ('exam_type', models.CharField(choices=[('1', 'Midterm'), ('2', 'Final'), ('3', 'Second Attempt'), ('4', 'Third Attempt')], default=1, max_length=255)),
                ('last_editor', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], default=1, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_tables', to='school_tables.ClassRoom')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_table', to='school_tables.TheClass')),
            ],
            options={
                'ordering': ['semester', 'exam_type', 'class_room'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('the_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_tables.Day')),
                ('exam_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school_tables.ExamTable')),
            ],
            options={
                'ordering': ['the_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_tables.TheClass'),
        ),
    ]
